### ISSUE TITLE
Mixing emmo 1.0.0-beta3 and 1.0.0-beta4

### ISSUE THREAD

**Issue by jesper-friis** [emmo-repo/domain-electrochemistry#40]
Electrochemistry indirectly imports both emmo 1.0.0-beta3 and 1.0.0-beta4.

The issue is that the modules `computerscience_bigmap`, `isq_bigmap` and `units_bigmap` explicitely imports emmo 1.0.0-beta3, while module `electrochemicalquantities` imports computerscience_big_map, which in turn import emmo 1.0.0-beta4.

My recommendation is to upgrade to emmo 1.0.0-beta4.

**Comment by jsimonclark** [comment]
upgraded to emmo 1.0.0-beta4.
